---
title: "Cell type annotation on GBM/HGG Xenium data"
author: "heinin"
date: "2025-10-11"
output:
  workflowr::wflow_html:
    code_folding: hide
  html_notebook: default
editor_options:
  chunk_output_type: console
---

### Import packages

```{r, warning=F, message=F}

suppressPackageStartupMessages({
  library(workflowr)
  library(arrow)
  library(Seurat)
  library(SeuratObject)
  library(SeuratDisk)
  library(tidyverse)
  library(tibble)
  library(ggplot2)
  library(ggpubr)
  library(ggrepel)
  library(googlesheets4)
  library(workflowr)})

```

### Environment variables and helper functions

```{r, message = F, warning = F}

setwd("/home/hnatri/13384_GBMHGG_SPP1_Xenium/")
set.seed(9999)
options(scipen = 99999)
options(ggrepel.max.overlaps = Inf)

#source("/home/hnatri/13384_GBMHGG_SPP1_Xenium/code/olors_themes.R")
source("/home/hnatri/13384_GBMHGG_SPP1_Xenium/code/plot_functions.R")

```

### Import data

```{r, message = F, warning = F, fig.width = 4, fig.height = 4}

# Copied to isilon /tgen_labs/banovich/PIPAC/Seurat
seurat_data <- readRDS("/tgen_labs/banovich/BCTCSF/13384_GBMHGG_Xenium/Seurat/spatial_clustered_NN30_PC50_Seurat.rds")

# Removing UnassignedCodewords from the expression data
seurat_data <- subset(seurat_data, features = rownames(seurat_data)[-grep("UnassignedCodeword", rownames(seurat_data))])

seurat_data <- NormalizeData(seurat_data)
seurat_data <- ScaleData(seurat_data)

# saveRDS(seurat_data, "/tgen_labs/banovich/BCTCSF/13384_GBMHGG_Xenium/Seurat/cell_clustered_NN30_PC50_Seurat.rds")

DimPlot(seurat_data,
        group.by = "leiden_1.0",
        #cols = main_cluster_col,
        reduction = "umap",
        raster = T,
        label = T) +
  coord_fixed(ratio = 1) +
  theme_classic() +
  NoLegend()

```

```{r, message = F, warning = F, fig.width = 4, fig.height = 7}

DimPlot(seurat_data,
        reduction = "sp",
        group.by = "leiden_1.0",
        raster = T,
        label = F) +
    coord_fixed(ratio = 1) +
    theme_minimal() +
    NoLegend() +
    ggtitle("TMA1_0069754")

```

### Feature expression

```{r, message = F, warning = F, fig.width = 10, fig.height = 5}

grep("OLIG", rownames(seurat_data), value = T)

plot_features <- c("PTPRC",
                   "CD3D", "CD3E", "CD4", "CD8A", # T cells
                   "STAT4", "STAT3", "GZMB",
                   "SELL", "CD19", # B cells
                   "CD68", "CD44", "MARCO", "APOE", "C1QB", "SPP1",
                   "MS4A1", # Lineage markers
                   "FN1", "COL1A1", # Fibroblasts
                   "TP53", "KIT", # Tumor
                   "EPCAM",
                   "OLIG1", "OLIG2")

DotPlot(seurat_data,
        group.by = "leiden_1.0",
        features = plot_features,
        cols = c("gray89", "tomato3")) +
  RotatedAxis()

```

```{r, message = F, warning = F, fig.width = 12, fig.height = 14}

FeaturePlot(seurat_data,
            slot = "data",
            features = plot_features,
            order = T,
            ncol = 5,
            reduction = "umap",
            raster = T,
            cols = c("gray89", "tomato3")) &
  coord_fixed(ratio = 1) &
  theme_bw() &
  NoLegend()

```


```{r, message = F, warning = F, fig.width = 12, fig.height = 30}

FeaturePlot(seurat_data,
            slot = "data",
            #split.by = "Sample",
            features = plot_features,
            order = T,
            reduction = "sp",
            raster = T,
            ncol = 4,
            cols = c("gray89", "tomato3")) &
  coord_fixed(ratio = 1) &
  theme_bw() &
  NoLegend()

```

### DenoIST

```{r, message = F, warning = F, fig.width = 10, fig.height = 4, eval = F}

DefaultAssay(seurat_data) <- "denoist_RNA"
DotPlot(seurat_data,
        group.by = "leiden_1.0",
        features = plot_features,
        cols = c("azure", "tomato3")) +
  RotatedAxis()

```

### Top cluster markers

```{r, message = F, warning = F, fig.width = 5, fig.height = 4}

Idents(seurat_data) <- seurat_data$"leiden_1.0"
cluster_markers <- FindAllMarkers(seurat_data,
                                  return.thresh = 0.01,
                                  logfc.threshold = 0.5,
                                  min.pct = 0.20,
                                  verbose = T)

table(cluster_markers$cluster)

#hist(cluster_markers$avg_log2FC, main = "", xlab = "avg_log2FC", breaks = 100)
#hist(cluster_markers$p_val, main = "", xlab = "p_val", breaks = 100)
#hist(cluster_markers$p_val_adj, main = "", xlab = "p_val_adj", breaks = 100)

top_cluster_markers <- cluster_markers %>%
  arrange(dplyr::desc(avg_log2FC)) %>%
  group_by(cluster) %>%
  dplyr::slice(1:10)

```


```{r, message = F, warning = F, fig.width = 6, fig.height = 18, eval = F}

create_dotplot_heatmap(seurat_object = seurat_data,
                       plot_features = unique(top_cluster_markers$gene),
                       group_var = "leiden_1.0",
                       group_colors = main_cluster_col,
                       column_title = "",
                       row_km = 5,
                       col_km = 5,
                       row.order = NULL,
                       col.order = NULL)

```

### Saving top markers and annotations

```{r, message = F, warning = F, fig.width = 6, fig.height = 6, eval = F}

output_cluster_markers <- cluster_markers %>%
  arrange(dplyr::desc(avg_log2FC)) %>%
  group_by(cluster) %>%
  dplyr::slice(1:30)

output_cluster_markers <- merge(top_cluster_markers, markers, by.x = "gene", by.y = "Gene")

write.table(output_cluster_markers, "/home/hnatri/13384_GBMHGG_SPP1_Xenium/main_cluster_markers.tsv",
            quote = F, row.names = F, sep = "\t")

# Saving DenoIST top markers by original annotation
Idents(seurat_data) <- seurat_data$Annotation
cluster_markers <- FindAllMarkers(seurat_data,
                                  return.thresh = 0.01,
                                  logfc.threshold = 0.5,
                                  min.pct = 0.20,
                                  verbose = T)

output_cluster_markers <- cluster_markers %>%
  arrange(dplyr::desc(avg_log2FC)) %>%
  group_by(cluster) %>%
  dplyr::slice(1:30)

output_cluster_markers <- merge(top_cluster_markers, markers, by.x = "gene", by.y = "Gene")

write.table(output_cluster_markers, "/home/hnatri/13384_GBMHGG_SPP1_Xenium/main_top_markers.tsv",
            quote = F, row.names = F, sep = "\t")

```

### Subsetting immune and non-immune cells for subclustering

```{r, message = F, warning = F, fig.width = 6, fig.height = 6, eval = F}

seurat_data$Lineage <- ifelse(seurat_data$leiden_0.5 %in% c(5, 6),
                              "Immune", "TumorStroma")

immune_subset <- subset(seurat_data, subset = Lineage == "Immune")
nonimmune_subset <- subset(seurat_data, subset = Lineage == "TumorStroma")

saveRDS(immune_subset, "/scratch/hnatri/13384_GBMHGG_SPP1_Xenium/cell_immune_subset.rds")
saveRDS(nonimmune_subset, "/scratch/hnatri/13384_GBMHGG_SPP1_Xenium/cell_nonimmune_subset.rds")

# To build on command line, run Rscript -e "rmarkdown::render('annotation_cell.Rmd')"
# Then "mv *.html /home/hnatri/13384_GBMHGG_SPP1_Xenium/docs/"

```

