---
title: "Niche analysis, N cells = 3k, N neighbors = 20"
author: "heinin"
date: "2026-01-09"
output:
  workflowr::wflow_html:
    code_folding: hide
  html_notebook: default
editor_options:
  chunk_output_type: console
---

### Load packages

```{r, warning=F, message=F}

suppressPackageStartupMessages({
  library(workflowr)
  library(arrow)
  library(Seurat)
  library(SeuratObject)
  library(SeuratDisk)
  library(tidyverse)
  library(tibble)
  library(plyr)
  library(ggplot2)
  library(ggpubr)
  library(ggrepel)
  library(googlesheets4)
  library(workflowr)
  library(patchwork)
  library(scProportionTest)})

```

### Environment variables and helper functions

```{r, message = F, warning = F}

setwd("/home/hnatri/13384_GBMHGG_SPP1_Xenium/")
set.seed(9999)
options(future.globals.maxSize = 30000 * 1024^2)
options(scipen = 99999)
options(ggrepel.max.overlaps = Inf)

#source("/home/hnatri/13384_GBMHGG_SPP1_Xenium/code/colors_themes.R")
source("/home/hnatri/13384_GBMHGG_SPP1_Xenium/code/plot_functions.R")

# Lineage info
gs4_deauth()
all_sheets  <- gs4_get("https://docs.google.com/spreadsheets/d/1V1YxYPMI-J1ilZ3ooTDM323s5VMIf7E9f5XsuIOaGAg/edit?usp=sharing")
sheet_names(all_sheets)
multissue_cancer <- read_sheet(all_sheets, sheet = "Multi-tissue and cancer basepanel")
custom_panel <- read_sheet(all_sheets, sheet = "Custom probes")
immune_annot <- read_sheet(all_sheets, sheet = "Immune annotations")
nonimmune_annot <- read_sheet(all_sheets, sheet = "Non-immune annotations")

all_annot <- rbind(immune_annot, nonimmune_annot)

# Calling DEGs between two groups for each cell type
get_DEGs <- function(seuratdata, ctvar, celltypes, groupvar, group1, group2){
  #message(xx)
  DEGlist <- lapply(celltypes, function(xx){
    seuratdata$DEGgroup <- seuratdata@meta.data[,ctvar]
    data_subset <- subset(seuratdata, subset = DEGgroup == xx)
    Idents(data_subset) <- as.character(unlist(data_subset[[groupvar]]))
    
    if (min(table(unlist(data_subset[[groupvar]])))<20){
      return(NULL)
    }
    
    if (all((c(group1, group2) %in% unlist(data_subset[[groupvar]]) == c(T, T)))){
      markers <- FindMarkers(data_subset,
                             ident.1 = group1,
                             ident.2 = group2,
                             assay = "RNA",
                             verbose = F)
      markers$feature <- rownames(markers)
      markers[,ctvar] <- xx
      
      return(markers)
    } else {
      return(NULL)
    }
    })
  
  as.data.frame(do.call(rbind, DEGlist))
}

```

### Import data

```{r, message = F, warning = F, fig.width = 8, fig.height = 4}

seurat_data <- readRDS("/tgen_labs/banovich/BCTCSF/13384_GBMHGG_Xenium/Seurat/immune_nonimmune_annotated_merged_Seurat_niches.rds")

```

### Niche construction

See /code/construct_niches.R

### Plotting niche composition

```{r, message = F, warning = F, fig.width = 12, fig.height = 4}

celltypes <- sort(unique(seurat_data$prelim_annot))
celltype_col <- colorRampPalette(brewer.pal(10, "Paired"))(nb.cols <- length(celltypes))
names(celltype_col) <- celltypes

plot_list <- lapply(seq(3, 8), function(niche){
  niche_column <- paste0("ncells3k_niche_k", niche, "_n20")
  niches <- seq(1, niche)
  seurat_data@meta.data[,niche_column] <- factor(seurat_data@meta.data[,niche_column],
                                                 levels = niches)
  
  create_barplot(seurat_data,
                 group_var = niche_column,
                 plot_var = "prelim_annot",
                 group_levels = niches,
                 plot_levels = sort(unique(seurat_data$prelim_annot)),
                 plot_colors = celltype_col,
                 var_names =  c("Frequency (%)", ""),
                 legend_title = "Cell type")
  
})


plot_list

```

### Plotting by group

```{r, message = F, warning = F, fig.width = 12, fig.height = 4, eval = F}

plot_list <- lapply(seq(3, 8), function(niche){
  niche_column <- paste0("ncells3k_niche_k", niche, "_n20")
  ct_table <- as.data.frame(table(seurat_data@meta.data[, niche_column], seurat_data$Tissue))
  colnames(ct_table) <- c("Niche", "Tissue", "Freq")
  ct_table <- spread(ct_table, Niche, Freq)
  # Converting to percetange
  #ct_table[,2:length(ct_table)] <- (ct_table[,2:length(ct_table)]/rowSums(ct_table[,2:length(ct_table)]))*100
  ct_table <- gather(ct_table, Niche, Freq, names(ct_table)[2:length(names(ct_table))], factor_key=TRUE)
      
  ct_table$Tissue <- factor(ct_table$Tissue, levels = c("Normal", "Tumor"))
  
  niches <- seq(1, niche)
  niches <- factor(niches, levels = niches)
  #niches <- sort(unique(seurat_data@meta.data[, niche_col]))
  niche_col <- colorRampPalette(brewer.pal(10, "Paired"))(nb.cols <- length(niches))
  names(niche_col) <- levels(niches)
  
  ggplot(ct_table, aes(x = Tissue, y = Freq, fill = Niche)) +
         geom_bar(stat="identity", position='stack', width = 0.8) +
         scale_fill_manual(name = "Niche", values = niche_col) +
         xlab("") +
         ylab("Cell count") +
         theme_classic() +
         theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))
  
})

plot_list

```

### Plotting by sample

```{r, message = F, warning = F, fig.width = 12, fig.height = 4, eval = T}

plot_list <- lapply(seq(3, 8), function(niche){
  niche_column <- paste0("ncells3k_niche_k", niche, "_n20")
  niches <- seq(1, niche)
  seurat_data@meta.data[,niche_column] <- factor(seurat_data@meta.data[,niche_column],
                                                 levels = niches)
  niche_col <- colorRampPalette(brewer.pal(10, "Paired"))(nb.cols <- length(niches))
  names(niche_col) <- levels(niches)
  
  create_barplot(seurat_data,
                 plot_var = niche_column,
                 group_var = "Sample",
                 plot_levels = niches,
                 group_levels = sort(unique(seurat_data$Sample)),
                 plot_colors = niche_col,
                 var_names =  c("Frequency (%)", ""),
                 legend_title = "Niche")
  
})

plot_list

```

### Spatial plots of niches

```{r, message = F, warning = F, fig.width = 8, fig.height = 5}

plot_list <- lapply(seq(3, 8), function(niche){
  
  niche_column <- paste0("ncells3k_niche_k", niche, "_n20")
  niches <- seq(1, niche)
  niches <- factor(niches, levels = niches)
  #niches <- sort(unique(seurat_data@meta.data[, niche_col]))
  niche_col <- colorRampPalette(brewer.pal(10, "Paired"))(nb.cols <- length(niches))
  names(niche_col) <- levels(niches)
  
  DimPlot(seurat_data,
          group.by = niche_column,
          cols = niche_col,
          reduction = "sp") +
  coord_fixed()
  
})

plot_list

```

### Dotplot of cell assignment to niches by celltype

```{r, message = F, warning = F, fig.width = 6, fig.height = 10}

niche_ct_prop <- table(seurat_data$prelim_annot, seurat_data$ncells3k_niche_k5_n20)
niche_ct_prop <- prop.table(niche_ct_prop, margin = 2)
niche_ct_prop <- niche_ct_prop %>%
  as.data.frame()

# Adding lineage
niche_ct_prop$lineage <- mapvalues(niche_ct_prop$Var1,
                                   from = all_annot$annotation,
                                   to = all_annot$lineage)

niche_ct_prop$Var1 <- factor(niche_ct_prop$Var1,
                             levels = rev(unique(niche_ct_prop$Var1)))

p1 <- ggplot(niche_ct_prop, aes(x = Var2, y = Var1)) +
  geom_point(aes(size = Freq, 
                 #color = value,
                 fill = Var1), 
             stroke = 0.5,
             shape = 21) +
  guides(color = FALSE) +
  scale_fill_manual(values = celltype_col) +
  theme_bw() +
  xlab("") +
  ylab("") +
  facet_grid(lineage ~ ., scales = "free", space = "free") +
  NoLegend()

# k6
niche_ct_prop <- table(seurat_data$prelim_annot, seurat_data$ncells3k_niche_k6_n20)
niche_ct_prop <- prop.table(niche_ct_prop, margin = 2)
niche_ct_prop <- niche_ct_prop %>%
  as.data.frame()

niche_ct_prop$lineage <- mapvalues(niche_ct_prop$Var1,
                                   from = all_annot$annotation,
                                   to = all_annot$lineage)

niche_ct_prop$Var1 <- factor(niche_ct_prop$Var1,
                             levels = rev(unique(niche_ct_prop$Var1)))

p2 <- ggplot(niche_ct_prop, aes(x = Var2, y = Var1)) +
  geom_point(aes(size = Freq, 
                 #color = value,
                 fill = Var1), 
             stroke = 0.5,
             shape = 21) +
  guides(color = FALSE) +
  scale_fill_manual(values = celltype_col) +
  theme_bw() +
  xlab("") +
  ylab("") +
  facet_grid(lineage ~ ., scales = "free", space = "free") +
  NoLegend()

# k7
niche_ct_prop <- table(seurat_data$prelim_annot, seurat_data$ncells3k_niche_k7_n20)
niche_ct_prop <- prop.table(niche_ct_prop, margin = 2)
niche_ct_prop <- niche_ct_prop %>%
  as.data.frame()

niche_ct_prop$lineage <- mapvalues(niche_ct_prop$Var1,
                                   from = all_annot$annotation,
                                   to = all_annot$lineage)

niche_ct_prop$Var1 <- factor(niche_ct_prop$Var1,
                             levels = rev(unique(niche_ct_prop$Var1)))

p3 <- ggplot(niche_ct_prop, aes(x = Var2, y = Var1)) +
  geom_point(aes(size = Freq, 
                 #color = value,
                 fill = Var1), 
             stroke = 0.5,
             shape = 21) +
  guides(color = FALSE) +
  scale_fill_manual(values = celltype_col) +
  theme_bw() +
  xlab("") +
  ylab("") +
  facet_grid(lineage ~ ., scales = "free", space = "free") +
  NoLegend()

p1

p2

p3

```

### Marker expression in niches

```{r, message = F, warning = F, fig.width = 5, fig.height = 4, eval = F}


# Rscript -e "rmarkdown::render('niche_construction_ncells3k_nneighbors20.Rmd')"

```
